# Generated by Django 3.0.9 on 2020-09-30 10:21

from django.db import migrations

def create_editor_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    editor_group = Group.objects.create(name='editor')
    permision = Permission.objects.get(codename="add_entry")
    editor_group.permissions.add(permision)
    permision = Permission.objects.get(codename="change_entry")
    editor_group.permissions.add(permision)
    permision = Permission.objects.get(codename="delete_entry")
    editor_group.permissions.add(permision)


def delete_editor_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='editor').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_editor_group, delete_editor_group)
    ]
